### ISSUE TITLE
Revise build script

### ISSUE THREAD

**Issue by jc-cisneros** [jc-cisneros/template#1]
This error is related to https://github.com/gentzkow/template/issues/58 on the original repo. The terminal session [Terminal Saved Output - JC.txt](https://github.com/jc-cisneros/template/files/9124416/Terminal.Saved.Output.-.JC.txt) includes the commands to pull the csv files using git lfs, the setup check, and the error when running the build script.

**Comment by jc-cisneros** [comment]
Summary: In this issue we coded a path for the build script.

Main comment is https://github.com/jc-cisneros/template/pull/4#issue-1306607400

Changes brought to main branch in 2d699f0

**Comment by anacarolinapq** [comment]
@jc-cisneros: thanks for addressing this issue! It was not super clear for me what the task + deliverables were here. Per the [RA Manual](https://github.com/gslab-econ/lab-manual/wiki/Issues#description):

> The issue description should state the goals of the issue clearly. Like the title, it should usually be written in imperative mode. The description should be precise enough that a third party can judge whether the issue was completed or not. It should include enough explanation and context that someone who is not intimately familiar with the other work going on at that moment can understand it clearly -- remember that we will often be returning to these issues many months or even years later and trying to understand what was going on.
