### ISSUE TITLE
Change y-axis in histogram to percentages

### ISSUE THREAD

**Issue by jc-cisneros** [jc-cisneros/template#2]
As required by [Practice Task](https://github.com/gslab-econ/ra-manual/wiki/Practice-Task). The deliverable is the updated figure after running the build script.

**Comment by anacarolinapq** [comment]
@jc-cisneros thanks!  One note: whenever possible the deliverables should be stable links (i.e. if we changed the figure in `master` with a new commit, the first link in https://github.com/jc-cisneros/template/issues/2#issuecomment-1187748701 would point to the updated figure, not the deliverable).
