### ISSUE TITLE
Add table with regression on the subset of years >= 1960

### ISSUE THREAD

**Issue by jc-cisneros** [jc-cisneros/template#3]
As required by [Practice Task](https://github.com/gslab-econ/ra-manual/wiki/Practice-Task). The steps to be taken are the following:

- Run an additional regression in the analysis module. The results should be a csv file in its corresponding output folder.
- Add the table with the results of the regression in the paper_slides module. Make sure that the csv file in the output folder of the analysis module is included in the input folder of the paper_slides module. 

The final result is an updated version of the paper that includes table 2 after running the build script from root.

**Comment by jc-cisneros** [comment]
Summary: In this issue we ran a new regression for the subset of the sample where year>=1960. We added a table in the paper with the results.

Main deliverable is Table 2 on [paper.pdf](https://github.com/jc-cisneros/template/blob/master/paper_slides/output/paper.pdf)

Changes brought to main branch in [b669a58](https://github.com/jc-cisneros/template/commit/b669a58845d9f37e0bdd8460ca99740292f7f403)

**Comment by anacarolinapq** [comment]
Nice description here https://github.com/jc-cisneros/template/issues/3#issue-1306605953! Same as in https://github.com/jc-cisneros/template/issues/2#issuecomment-1245968875 goes for stable links.
